import { Implements } from "../definitions/Implements";
import { ImplementsResponse } from "../definitions/ImplementsResponse";
import { CheckServiceActivity } from "../definitions/CheckServiceActivity";
import { CheckServiceActivityResponse } from "../definitions/CheckServiceActivityResponse";
import { GetSchema } from "../definitions/GetSchema";
import { GetSchemaResponse } from "../definitions/GetSchemaResponse";
import { IsValidDataServer } from "../definitions/IsValidDataServer";
import { IsValidDataServerResponse } from "../definitions/IsValidDataServerResponse";
import { GetSchemaEmail } from "../definitions/GetSchemaEmail";
import { GetSchemaEmailResponse } from "../definitions/GetSchemaEmailResponse";
import { ReadView } from "../definitions/ReadView";
import { ReadViewResponse } from "../definitions/ReadViewResponse";
import { ReadViewEmail } from "../definitions/ReadViewEmail";
import { ReadViewEmailResponse } from "../definitions/ReadViewEmailResponse";
import { ReadRecord } from "../definitions/ReadRecord";
import { ReadRecordResponse } from "../definitions/ReadRecordResponse";
import { ReadRecordEmail } from "../definitions/ReadRecordEmail";
import { ReadRecordEmailResponse } from "../definitions/ReadRecordEmailResponse";
import { SaveRecord } from "../definitions/SaveRecord";
import { SaveRecordResponse } from "../definitions/SaveRecordResponse";
import { SaveRecordEmail } from "../definitions/SaveRecordEmail";
import { SaveRecordEmailResponse } from "../definitions/SaveRecordEmailResponse";
import { DeleteRecord } from "../definitions/DeleteRecord";
import { DeleteRecordResponse } from "../definitions/DeleteRecordResponse";
import { DeleteRecordEmail } from "../definitions/DeleteRecordEmail";
import { DeleteRecordEmailResponse } from "../definitions/DeleteRecordEmailResponse";
import { DeleteRecordByKey } from "../definitions/DeleteRecordByKey";
import { DeleteRecordByKeyResponse } from "../definitions/DeleteRecordByKeyResponse";
import { ReadLookupView } from "../definitions/ReadLookupView";
import { ReadLookupViewResponse } from "../definitions/ReadLookupViewResponse";
import { ReadLookupViewEmail } from "../definitions/ReadLookupViewEmail";
import { ReadLookupViewEmailResponse } from "../definitions/ReadLookupViewEmailResponse";

export interface RmIwsDataServer {
    Implements(teste: Implements, callback: (err: any, result: ImplementsResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    CheckServiceActivity(checkServiceActivity: CheckServiceActivity, callback: (err: any, result: CheckServiceActivityResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSchema(getSchema: GetSchema, callback: (err: any, result: GetSchemaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    IsValidDataServer(isValidDataServer: IsValidDataServer, callback: (err: any, result: IsValidDataServerResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    GetSchemaEmail(getSchemaEmail: GetSchemaEmail, callback: (err: any, result: GetSchemaEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadView(readView: ReadView, callback: (err: any, result: ReadViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadViewEmail(readViewEmail: ReadViewEmail, callback: (err: any, result: ReadViewEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadRecord(readRecord: ReadRecord, callback: (err: any, result: ReadRecordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadRecordEmail(readRecordEmail: ReadRecordEmail, callback: (err: any, result: ReadRecordEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SaveRecord(saveRecord: SaveRecord, callback: (err: any, result: SaveRecordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    SaveRecordEmail(saveRecordEmail: SaveRecordEmail, callback: (err: any, result: SaveRecordEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteRecord(deleteRecord: DeleteRecord, callback: (err: any, result: DeleteRecordResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteRecordEmail(deleteRecordEmail: DeleteRecordEmail, callback: (err: any, result: DeleteRecordEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    DeleteRecordByKey(deleteRecordByKey: DeleteRecordByKey, callback: (err: any, result: DeleteRecordByKeyResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadLookupView(readLookupView: ReadLookupView, callback: (err: any, result: ReadLookupViewResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    ReadLookupViewEmail(readLookupViewEmail: ReadLookupViewEmail, callback: (err: any, result: ReadLookupViewEmailResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
