# Version: 1.0.1
name: Auto Generate README

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    if: startsWith(github.event.repository.name, 'th-')
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.README_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g typescript ts-node

      - name: Clone README Generator
        run: |
          git clone https://x-access-token:${{ secrets.README_TOKEN }}@github.com/4success/github-readme-generator.git
          cd github-readme-generator
          npm install

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
          GITHUB_ORG: '4success'
          LLM_PROVIDER: 'claude'
          LLM_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
          GIT_CREDENTIALS: https://x-access-token:${{ secrets.README_TOKEN }}@github.com
        run: |
          cd github-readme-generator
          git config --global credential.helper store
          echo "$GIT_CREDENTIALS" > ~/.git-credentials
          ts-node src/index.ts --single-repo ${{ github.event.repository.name }}

      - name: Commit README if Changed
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "docs: update README.md [skip ci]"
            git push
          fi