# Version: 1.0.0
name: Auto Generate README

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  check-repo:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.repository.name }}" =~ ^th- ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  generate-readme:
    needs: check-repo
    if: needs.check-repo.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.README_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm install -g typescript ts-node

      - name: Clone README Generator
        run: |
          git clone https://x-access-token:${{ secrets.README_TOKEN }}@github.com/4success/github-readme-generator.git
          cd github-readme-generator
          npm install

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
          GITHUB_ORG: '4success'
          LLM_PROVIDER: 'claude'
          LLM_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          cd github-readme-generator
          ts-node src/index.ts --single-repo ${{ github.event.repository.name }}

      - name: Commit README if Changed
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "docs: update README.md [skip ci]"
            git push
          fi