# Version: 1.0.6
name: Auto Generate README

on:
  push:
    branches: [main, master]
    paths-ignore: ['README.md']
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    if: startsWith(github.event.repository.name, 'th-')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.README_TOKEN}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config --global url."https://x-access-token:${{secrets.README_TOKEN}}@github.com/".insteadOf "https://github.com/"

      - name: Install Dependencies
        run: npm install -g typescript ts-node

      - name: Clone README Generator
        run: |
          git clone https://x-access-token:${{secrets.README_TOKEN}}@github.com/4success/github-readme-generator.git
          cd github-readme-generator
          npm install

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{secrets.README_TOKEN}}
          GITHUB_ORG: '4success'
          LLM_PROVIDER: 'claude'
          LLM_MODEL: 'claude-3-5-haiku-latest'
          LLM_API_KEY: ${{secrets.CLAUDE_API_KEY}}
        run: |
          cd github-readme-generator
          ts-node src/index.ts --single-repo ${{github.event.repository.name}}

      - name: Commit README if Changed
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "docs: update README.md [skip ci]"
            git push
          fi